version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.11.0-browsers
        environment:
          NODE_ENV: development
          MONGODB_TEST_URI: 'mongodb://localhost:27017/openChatTest'
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: Start MongoDB
          command: docker run --net=host mongo
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait mongodb://localhost:27017 -timeout 60s
      - run:
          name: Test
          command: yarn test
